[project]
name = "orbis"
version = "0.1.0"
description = "Orbis — your best and most attentive listener!"
requires-python = ">=3.12"
authors = [
    { name = "Ivanchenko Yaroslav", email = "zerowkacp@gmail.com" },
]

dependencies = [
    "fastapi[standard]>=0.141.1",
    "faster-whisper>=1.2.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "sqlalchemy>=2.0.52",
    "websockets>=17.0.1",
]

[tool.fastapi]
entrypoint = "backend.src.main:app"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
