"""add color column to categories

Revision ID: 7b34a5acb644
Revises: ad148c819be2
Create Date: 2026-08-06 22:08:38.965689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b34a5acb644'
down_revision: Union[str, Sequence[str], None] = 'ad148c819be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_categories', sa.Column('color', sa.String(length=7), nullable=False))
    op.create_check_constraint('ck_note_category_color', 'note_categories', "color ~ '^#[0-9A-Fa-f]{6}$'")
    op.add_column('notes', sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'created_at')
    op.drop_constraint('ck_note_category_color', 'note_categories', type_='check')
    op.drop_column('note_categories', 'color')
    # ### end Alembic commands ###
