"""temporary decision to make user_id nullable

Revision ID: ad148c819be2
Revises: 6fbb04816914
Create Date: 2026-08-05 22:42:35.231736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad148c819be2'
down_revision: Union[str, Sequence[str], None] = '6fbb04816914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('note_categories', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('notes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('note_categories', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
