name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Check secrets
        env:
            GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
            if [ -z "$GEMINI_API_KEY" ]; then
            echo "GEMINI_API_KEY is missing"
            exit 1
            fi

            if [ -z "$POSTGRES_PASSWORD" ]; then
            echo "POSTGRES_PASSWORD is missing"
            exit 1
            fi

            echo "Required secrets are present"

      - name: Create environment
        run: |
            cp backend/.env.test backend/.env
            echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> backend/.env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> backend/.env

      - name: Run Database
        run: docker compose up -d postgres

      - name: Run Tests
        run: docker compose run --rm backend pytest

      - name: Stop Containers
        if: always()
        run: docker compose down -v